const getGeneratePrompt = (
    promptId: string,
    jobTitle: string,
    length: number
) => {
    switch (promptId) {
        case "summary":
            return `Write a summary section for a ${jobTitle} resume. Ensure that it is ${length} words long and targeted to this job's industry and role and that it does not sound obviously generated by an AI.`;
        case "experience":
            return `Write a short general resume summary.`;
        case "education":
            return `Write a short general resume summary.`;
        case "skills":
            return `Write a short general resume summary.`;
        case "languages":
            return `Write a short general resume summary.`;
        case "interests":
            return `Write a short general resume summary.`;
        case "projects":
            return `Write a short general resume summary.`;
        default:
            return `Write a short general resume summary.`;
    }
};

const getEnhancePrompt = (
    promptId: string,
    jobTitle: string,
    length: number,
    currentText: string
) => {
    switch (promptId) {
        case "summary":
            return `Enhance the following summary section for a ${jobTitle} resume. Ensure that it is ${length} words long and targeted to this job's industry and role and that it does not sound obviously generated by an AI. Current text: ${currentText}`;
        case "experience":
            return `Enhance the experience section for a ${jobTitle} resume. Ensure that it is ${length} words long and targeted to this job's industry and role and that it does not sound obviously generated by an AI.`;
        case "education":
            return `Enhance the education section for a ${jobTitle} resume. Ensure that it is ${length} words long and targeted to this job's industry and role and that it does not sound obviously generated by an AI.`;
        case "skills":
            return `Enhance the skills section for a ${jobTitle} resume. Ensure that it is ${length} words long and targeted to this job's industry and role and that it does not sound obviously generated by an AI.`;
        case "languages":
            return `Enhance the languages section for a ${jobTitle} resume. Ensure that it is ${length} words long and targeted to this job's industry and role and that it does not sound obviously generated by an AI.`;
        case "interests":
            return `Enhance the interests section for a ${jobTitle} resume. Ensure that it is ${length} words long and targeted to this job's industry and role and that it does not sound obviously generated by an AI.`;
        case "projects":
            return `Enhance the projects section for a ${jobTitle} resume. Ensure that it is ${length} words long and targeted to this job's industry and role and that it does not sound obviously generated by an AI.`;
        default:
            return "";
    }
};

export const getPrompt = (data: {
    promptId: string;
    document: any;
    generate: boolean;
    enhance: boolean;
    length: number;
    currentText?: string;
}) => {
    const { promptId, document, generate, enhance, length } = data;
    let jobTitle = document?.information.jobTitle;
    if (generate) {
        return getGeneratePrompt(promptId, jobTitle, length);
    } else if (enhance && data.currentText) {
        return getEnhancePrompt(promptId, jobTitle, length, data.currentText);
    }
};
