export const sampleResumesArray = [
    {
        currentPage: 1,
        information: {
            font: "Times-Roman",
            style: {
                textColor: "#000000",
                baseFontSize: 12,
                baseMarginSize: 18,
                baseSectionGap: 16,
                accentTextColor: "white",
                backgroundColor: "#ffffff",
                accentBackgroundColor: "#b5b357",
            },
            summary:
                "Experienced Marketing Manager with a proven track record of developing and implementing successful marketing strategies across digital, social media, and traditional channels to drive brand awareness and lead generation. Skilled in market research, trend analysis, and campaign management. Collaborative team player adept at creating compelling marketing collateral and optimizing campaign performance through data-driven insights. Strong project management abilities and a passion for innovation. Bachelor's degree in Marketing with over 3 years of relevant experience. Proficient in marketing analytics tools. Committed to staying updated on industry trends to enhance marketing efforts continually.",
            imageUrl: "/images/icons/default-profile-picture.svg",
            jobTitle: "Marketing Manager",
            lastName: "Johnson",
            numPages: 1,
            position: "Marketing Coordinator",
            template: "sharp",
            firstName: "Emma",
            skillArray: [
                "Develop and implement data-driven marketing strategies across digital, social media, and traditional channels.",
                "Implementing strategic market research to identify trends, consumer behavior, and growth opportunities effectively.",
                "Craft compelling brand messaging that resonates with target audiences and drives customer engagement.",
                "Demonstrate expertise in market segmentation to target and reach diverse audience demographics effectively.",
                "Utilize advanced marketing analytics tools to optimize campaign performance and drive data-informed decisions.",
                "Analyze marketing campaign performance to optimize strategies and achieve company objectives effectively.",
            ],
            contactInfo: {
                email: "EmmaJohnson@Example.com",
                phone: "(123) 456-7890",
                website: "EmmaJohnson.com",
            },
            currentPage: 1,
            description:
                "Resume for Marketing Manager application at ABC Marketing Agency",
            sectionEdit: {
                name: { fontRatio: 1, textAlignment: "center" },
                header: {
                    fontRatio: 1,
                    showSocial: true,
                    showSummary: true,
                    showPosition: true,
                },
                skills: { fontRatio: 1, textAlignment: "left" },
                contact: {
                    fontRatio: 1,
                    showEmail: true,
                    showPhone: true,
                    showWebsite: true,
                    textAlignment: "left",
                },
                summary: { fontRatio: 1, textAlignment: "left" },
                position: { fontRatio: 1, textAlignment: "center" },
                projects: { fontRatio: 1, showSummary: true },
                education: {
                    showGpa: false,
                    fontRatio: 1,
                    dateFormat: "long",
                    showBullets: true,
                    showStartDate: true,
                },
                interests: { fontRatio: 1, textAlignment: "left" },
                languages: { fontRatio: 1, textAlignment: "left" },
                experience: {
                    fontRatio: 1,
                    dateFormat: "long",
                    showSummary: true,
                    showStartDate: true,
                },
            },
            documentName: "Emma-Johnson-Resume",
            projectArray: [
                {
                    demo: "https://example-demo-link.com",
                    name: "Example Project Name",
                    source: "https://example-source-link.com",
                    bullets: [
                        "Example bullet 1.",
                        "Example bullet 2.",
                        "Example bullet 3.",
                    ],
                    summary: "Example summary.",
                },
                {
                    demo: "https://example-demo-link.com",
                    name: "Example Project Name 2",
                    source: "https://example-source-link.com",
                    bullets: [
                        "Example bullet 1.",
                        "Example bullet 2.",
                        "Example bullet 3.",
                    ],
                    summary: "Example summary.",
                },
            ],
            sectionOrder: [
                [
                    "headerSharp",
                    "summary",
                    "educationDetailed",
                    "experience",
                    "skillsBullet",
                    "languagesComma",
                ],
            ],
            interestArray: ["interest 1", "interest 2", "interest 3"],
            languageArray: ["English", "Spanish"],
            summaryConfig: {
                isBold: false,
                isItalic: false,
                textColor: "#000000",
                isUnderline: false,
                sectionTitle: "Summary",
                fontSizeRatio: 1,
            },
            educationArray: [
                {
                    id: 1,
                    gpa: "",
                    bullets: [],
                    endDate: "2020-06-16",
                    startDate: "2016-06-16",
                    degreeType: "Bachelor's Degree",
                    schoolName: "ABC University",
                    degreeField: "Marketing",
                    currentEnrollment: false,
                },
            ],
            jobDescription:
                'ob Title: Marketing Manager\r\n\r\nCompany: XYZ Marketing Solutions\r\n\r\nLocation: Anytown, USA\r\n\r\nJob Description:\r\nXYZ Marketing Solutions is seeking a dynamic and experienced Marketing Manager to join our team. The Marketing Manager will be responsible for developing and implementing strategic marketing plans to drive brand awareness and lead generation. This role will involve collaborating with cross-functional teams, managing marketing campaigns, analyzing market trends, and overseeing the execution of marketing initiatives.\r\n\r\nResponsibilities:\r\n\r\nDevelop and execute comprehensive marketing strategies to achieve company objectives\r\nManage marketing campaigns across multiple channels, including digital, social media, email, and traditional advertising\r\nConduct market research and analyze consumer behavior to identify trends and opportunities\r\nCollaborate with internal teams to create compelling marketing collateral, including website content, social media posts, and promotional materials\r\nMonitor and report on the performance of marketing campaigns, using data-driven insights to optimize results\r\nStay up-to-date with industry trends and best practices to continually improve marketing efforts\r\nQualifications:\r\n\r\nBachelor\'s degree in Marketing, Business Administration, or related field\r\nProven track record of success in marketing, with at least 3 years of experience in a similar role\r\nStrong project management skills, with the ability to manage multiple priorities and deadlines\r\nExcellent communication and interpersonal skills, with the ability to collaborate effectively with cross-functional teams\r\nProficiency in marketing analytics tools and techniques\r\nCreative thinker with a passion for innovation and problem-solving\r\nBenefits:\r\n\r\nCompetitive salary and performance-based bonuses\r\nComprehensive health and wellness benefits package\r\nOpportunities for professional development and advancement\r\nFun and collaborative work environment with team-building activities\r\nFlexible work schedule and remote work options\r\nHow to Apply:\r\nInterested candidates should submit their resume and cover letter to [email address] with the subject line "Marketing Manager Application". Please include examples of previous marketing campaigns and results achieved.',
            experienceArray: [
                {
                    bullets: [
                        "Developed and executed data-driven marketing strategies, resulting in a 20% increase in lead generation.",
                        "Implemented targeted email campaigns resulting in a 25% increase in customer engagement and retention.",
                        "Led cross-functional team in developing and launching successful marketing campaigns across various channels.",
                    ],
                    company: "XYZ Company",
                    endDate: "Present",
                    summary:
                        "Successfully executed multichannel marketing campaigns, analyzed consumer behavior, and optimized results for brand awareness and lead generation. Developed compelling marketing collateral with cross-functional teams, driving engagement and increasing conversions.",
                    position: "Marketing Coordinator",
                    startDate: "2023-06-16",
                    currentEmployer: true,
                },
                {
                    bullets: [
                        "Boosted brand engagement by 30% through interactive social media campaigns and targeted content strategies.",
                        "Implemented social media ad campaigns, increasing lead generation by 25% for XYZ Marketing Solutions.",
                        "Revamped social media content strategy, resulting in 50% increase in audience engagement for XYZ.",
                    ],
                    company: "ABC Company",
                    endDate: "2023-06-05",
                    summary:
                        "Developed impactful social media strategies and managed campaigns across platforms, increasing engagement by 40% and driving lead generation by 25%. Collaborated with teams to create compelling content.",
                    position: "Social Media Specialist",
                    startDate: "2020-06-16",
                    currentEmployer: false,
                },
            ],
            customSectionArray: [],
            skillCategoryArray: [
                {
                    skills: [
                        "Example Skill 1",
                        "Example Skill 2",
                        "Example Skill 3",
                    ],
                    category: "Example Category 1",
                },
                {
                    skills: [
                        "Example Skill 1",
                        "Example Skill 2",
                        "Example Skill 3",
                    ],
                    category: "Example Category 2",
                },
            ],
        },
    },

    {
        currentPage: 1,
        information: {
            font: "Times-Roman",
            style: {
                textColor: "#000000",
                baseFontSize: 12,
                baseMarginSize: 18,
                baseSectionGap: 16,
                accentTextColor: "white",
                backgroundColor: "#ffffff",
                accentBackgroundColor: "#698bd7",
            },
            summary:
                "Results-driven Senior Software Engineer with over 8 years of experience in designing and developing innovative software solutions. Skilled in full-stack development and proficient in multiple programming languages, including Java, Python, and JavaScript. Demonstrated expertise in leading cross-functional teams to deliver projects on time and within budget. Proven track record of improving system efficiency and performance through strategic problem-solving and analytical thinking. Adept at identifying opportunities for process optimization and implementing scalable solutions to drive business growth. Passionate about staying current with industry trends and technologies to deliver cutting-edge solutions.",
            imageUrl: "/images/icons/default-profile-picture.svg",
            jobTitle: "Senior Software Engineer",
            lastName: "Smith",
            numPages: 1,
            position: "Software Engineer",
            template: "fresh",
            firstName: "John",
            skillArray: [
                "Expertise in developing scalable and high-performance software solutions using modern programming languages and frameworks.",
                "Strong aptitude for problem-solving and optimizing algorithms for seamless integration within software applications.",
                "Proficient in conducting code reviews and mentoring junior team members to enhance code quality.",
                "Demonstrated ability to design and architect complex software systems for optimal performance and scalability.",
            ],
            contactInfo: {
                email: "JohnSmith@example.com",
                phone: "(123) 456-7890",
                website: "JohnSmith.com",
            },
            currentPage: 1,
            description:
                "Resume for Senior Software Engineer application at XYZ Company",
            sectionEdit: {
                name: { fontRatio: 1, textAlignment: "center" },
                header: {
                    fontRatio: 1,
                    showSocial: true,
                    showSummary: true,
                    showPosition: true,
                },
                skills: { fontRatio: 1, textAlignment: "left" },
                contact: {
                    fontRatio: 1,
                    showEmail: true,
                    showPhone: true,
                    showWebsite: true,
                    textAlignment: "left",
                },
                summary: { fontRatio: 1, textAlignment: "left" },
                position: { fontRatio: 1, textAlignment: "center" },
                projects: { fontRatio: 1, showSummary: true },
                education: {
                    showGpa: false,
                    fontRatio: 1,
                    dateFormat: "long",
                    showBullets: true,
                    showStartDate: false,
                },
                interests: { fontRatio: 1, textAlignment: "left" },
                languages: { fontRatio: 1, textAlignment: "left" },
                experience: {
                    fontRatio: 1,
                    dateFormat: "long",
                    showSummary: true,
                    showStartDate: true,
                },
            },
            documentName: "John-Smith-Resume",
            projectArray: [
                {
                    demo: "https://example-demo-link.com",
                    name: "Example Project Name",
                    source: "https://example-source-link.com",
                    bullets: [
                        "Example bullet 1.",
                        "Example bullet 2.",
                        "Example bullet 3.",
                    ],
                    summary: "Example summary.",
                },
                {
                    demo: "https://example-demo-link.com",
                    name: "Example Project Name 2",
                    source: "https://example-source-link.com",
                    bullets: [
                        "Example bullet 1.",
                        "Example bullet 2.",
                        "Example bullet 3.",
                    ],
                    summary: "Example summary.",
                },
            ],
            sectionOrder: [
                [
                    "headerFresh",
                    "summary",
                    "experience",
                    "educationDetailed",
                    "skillsCategory",
                ],
            ],
            interestArray: ["interest 1", "interest 2", "interest 3"],
            languageArray: ["langauge 1", "language 2", "language 3"],
            summaryConfig: {
                isBold: false,
                isItalic: false,
                textColor: "#000000",
                isUnderline: false,
                sectionTitle: "Summary",
                fontSizeRatio: 1,
            },
            educationArray: [
                {
                    id: 1,
                    gpa: "",
                    bullets: [],
                    endDate: "2020-07-16",
                    startDate: "2018-06-05",
                    degreeType: "Master's Degree",
                    schoolName: "Example University",
                    degreeField: "Computer Science",
                    currentEnrollment: false,
                },
                {
                    id: 2,
                    gpa: "",
                    bullets: [],
                    endDate: "2018-07-11",
                    startDate: "2014-06-10",
                    degreeType: "Bachelor's Degree",
                    schoolName: "Example University",
                    degreeField: "Computer Science",
                    currentEnrollment: false,
                },
            ],
            jobDescription: "",
            experienceArray: [
                {
                    bullets: [
                        "Developed scalable web applications, increasing user engagement by 25% through performance optimization strategies.",
                        "Collaborated in cross-functional teams to implement agile software development methodologies for enhanced productivity.",
                        "Enhanced website security by implementing robust protocols, reducing data breach incidents by 30%.",
                    ],
                    company: "Digital Solutions Inc",
                    endDate: "2023-01-31",
                    summary:
                        "Led full-stack web development projects, optimizing code for efficiency. Increased website load speed by 40% through performance enhancements. Created user-friendly interfaces for seamless navigation and engagement.",
                    position: "Web Developer",
                    startDate: "2022-02-01",
                    currentEmployer: false,
                },
                {
                    bullets: [
                        "Implemented agile methodologies leading to a 20% increase in project efficiency and collaboration.",
                        "Optimized code performance resulting in a 15% reduction in production bugs and errors.",
                        "Collaborated with cross-functional teams to deliver scalable software solutions meeting business objectives.",
                    ],
                    company: "Tech Corp",
                    endDate: "Present",
                    summary:
                        "Led full-stack development of web applications, optimizing performance and user experience. Increased efficiency by 25% through automation, resulting in enhanced user satisfaction and engagement.",
                    position: "Software Engineer",
                    startDate: "2023-02-16",
                    currentEmployer: true,
                },
            ],
            customSectionArray: [],
            skillCategoryArray: [
                {
                    skills: [
                        "Crafting efficient, scalable code solutions",
                        "Proficient in modern programming languages.",
                        "Building robust and secure applications.",
                        "Implementing innovative algorithms for optimization.",
                    ],
                    category: "Software Development Skills",
                },
                {
                    skills: [
                        "Custom Software Development and Integration",
                        "Full-Stack Web Development and Deployment",
                        "Agile Methodologies and Project Management",
                        "Cross-Platform Mobile App Development.",
                    ],
                    category: "Technical Expertise",
                },
                {
                    skills: [
                        "Proficient in Object-Oriented Programming",
                        "Skilled in Full Stack Development",
                        "Strong Problem-Solving Skills in Coding",
                        "Competent in Agile Software Development",
                    ],
                    category: "Programming Proficiency",
                },
            ],
        },
    },

    {
        currentPage: 1,
        information: {
            font: "Times-Roman",
            style: {
                textColor: "#000000",
                baseFontSize: 12,
                baseMarginSize: 18,
                baseSectionGap: 16,
                accentTextColor: "white",
                backgroundColor: "#ffffff",
                accentBackgroundColor: "#5d906c",
            },
            summary:
                "Highly skilled and compassionate Nurse Practitioner with a proven track record of providing comprehensive patient care in various healthcare settings. Possessing a strong clinical background, I am adept at conducting assessments, creating and implementing care plans, and providing patient education. Dedicated to delivering quality healthcare and promoting patient well-being through a holistic approach. Proficient in collaborating with multidisciplinary teams to ensure optimal patient outcomes. Recognized for excellent communication skills and ability to build trusting relationships with patients and families. Committed to staying current with medical advancements and best practices to deliver evidence-based care.",
            imageUrl: "/images/icons/default-profile-picture.svg",
            jobTitle: "Nurse Practicioner",
            lastName: "Chen",
            numPages: 1,
            position: "Nurse Practicioner",
            template: "nexus",
            firstName: "Emily",
            skillArray: [
                "Highly skilled in performing advanced health assessments, diagnosing illnesses, and developing comprehensive treatment plans.",
                "Expert in providing evidence-based care, collaborating with interdisciplinary teams, and delivering patient-centered interventions.",
                "Proficient in managing acute and chronic conditions with a focus on preventive care.",
                "Skilled in facilitating patient education and promoting optimal health outcomes through personalized care plans.",
                "Proficient in conducting procedures such as suturing wounds and administering injections for patient care.",
            ],
            contactInfo: {
                email: "EmilyChen@example.com",
                phone: "(123) 456-7890",
                website: "EmilyChen.com",
            },
            currentPage: 1,
            description:
                "Resume for Nurse Practicioner application at XYZ Company",
            sectionEdit: {
                name: { fontRatio: 1, textAlignment: "center" },
                header: {
                    fontRatio: 1,
                    showSocial: true,
                    showSummary: true,
                    showPosition: true,
                },
                skills: { fontRatio: 1, textAlignment: "left" },
                contact: {
                    fontRatio: 1,
                    showEmail: true,
                    showPhone: true,
                    showWebsite: true,
                    textAlignment: "left",
                },
                summary: { fontRatio: 1, textAlignment: "left" },
                position: { fontRatio: 1, textAlignment: "center" },
                projects: { fontRatio: 1, showSummary: true },
                education: {
                    showGpa: false,
                    fontRatio: 1,
                    dateFormat: "long",
                    showBullets: true,
                    showStartDate: false,
                },
                interests: { fontRatio: 1, textAlignment: "left" },
                languages: { fontRatio: 1, textAlignment: "left" },
                experience: {
                    fontRatio: 1,
                    dateFormat: "long",
                    showSummary: true,
                    showStartDate: true,
                },
            },
            documentName: "Emily-Chen-Resume",
            projectArray: [
                {
                    demo: "https://example-demo-link.com",
                    name: "Example Project Name",
                    source: "https://example-source-link.com",
                    bullets: [
                        "Example bullet 1.",
                        "Example bullet 2.",
                        "Example bullet 3.",
                    ],
                    summary: "Example summary.",
                },
                {
                    demo: "https://example-demo-link.com",
                    name: "Example Project Name 2",
                    source: "https://example-source-link.com",
                    bullets: [
                        "Example bullet 1.",
                        "Example bullet 2.",
                        "Example bullet 3.",
                    ],
                    summary: "Example summary.",
                },
            ],
            sectionOrder: [
                [
                    "headerNexus",
                    "summary",
                    "experience",
                    "educationDetailed",
                    "skillsBullet",
                    "languagesComma",
                ],
            ],
            interestArray: ["interest 1", "interest 2", "interest 3"],
            languageArray: ["English", "Spanish"],
            summaryConfig: {
                isBold: false,
                isItalic: false,
                textColor: "#000000",
                isUnderline: false,
                sectionTitle: "Summary",
                fontSizeRatio: 1,
            },
            educationArray: [
                {
                    id: 1,
                    gpa: "",
                    bullets: [],
                    endDate: "2021-07-07",
                    startDate: "2017-02-15",
                    degreeType: "Bachelor's Degree",
                    schoolName: "Example University",
                    degreeField: "Nursing",
                    currentEnrollment: false,
                },
            ],
            jobDescription: "",
            experienceArray: [
                {
                    bullets: [
                        "Administered over 500 vaccines and screenings, ensuring compliance with healthcare standards and protocols.",
                        "Educated patients on post-discharge care instructions to enhance recovery and treatment outcomes.",
                        "Collaborated with interdisciplinary team to develop and implement individualized care plans for patients.",
                    ],
                    company: "City Hospital",
                    endDate: "Present",
                    summary:
                        "Managed patient care for diverse populations, achieving a 15% increase in patient satisfaction scores. Led training sessions for new nurses, improving department efficiency by 20%.",
                    position: "Registered Nurse",
                    startDate: "2022-06-16",
                    currentEmployer: true,
                },
                {
                    bullets: [
                        "- Administered medications and treatments, achieving a 95% patient satisfaction rate for care provided.",
                        "Collaborated with healthcare team to develop patient care plans, resulting in improved patient outcomes.",
                        "Performed phlebotomy procedures with a 98% accuracy rate, supporting efficient diagnostic processes.",
                    ],
                    company: "Private Practice Clinic",
                    endDate: "2022-01-03",
                    summary:
                        "Led patient intake process and assisted with exams. Managed medical records and achieved 95% patient satisfaction. Supportive team player with strong communication skills.",
                    position: "Medical Assistant",
                    startDate: "2021-10-12",
                    currentEmployer: false,
                },
            ],
            customSectionArray: [],
            skillCategoryArray: [
                {
                    skills: [
                        "Example Skill 1",
                        "Example Skill 2",
                        "Example Skill 3",
                    ],
                    category: "Example Category 1",
                },
                {
                    skills: [
                        "Example Skill 1",
                        "Example Skill 2",
                        "Example Skill 3",
                    ],
                    category: "Example Category 2",
                },
            ],
        },
    },
];
